-- Add 45 sample tokens with diverse data
INSERT INTO tokens (
  name, 
  symbol, 
  address, 
  description, 
  story, 
  image_url, 
  created_by, 
  telegram, 
  email, 
  twitter, 
  dexscreener, 
  featured, 
  status, 
  good_lores
) VALUES 
-- Meme Coins
(
  'PepeFrog', 
  '$PEPEFROG', 
  '0x1a2b3c4d5e6f7890abcdef1234567890abcdef12', 
  'The ultimate Pepe evolution with frog powers and meme magic.', 
  'PepeFrog emerged from the depths of meme culture when the original Pepe met a magical frog in the swamps of 4chan. This fusion created the most powerful meme coin ever conceived, combining the viral nature of Pepe with the ancient wisdom of frogs. The community believes that holding PepeFrog grants you the power to predict market movements through amphibian intuition.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@pepefrog', 
  'team@pepefrog.meme', 
  'https://twitter.com/pepefrog', 
  'https://dexscreener.com/ethereum/0x1a2b3c4d', 
  TRUE, 
  'approved', 
  892
),
(
  'DogeKing', 
  '$DOGEKING', 
  '0x2b3c4d5e6f7890abcdef1234567890abcdef1234', 
  'The royal evolution of Doge, ruling the meme kingdom with wisdom and wow.', 
  'DogeKing was born when the original Doge achieved enlightenment after years of "much wow" and "very crypto." Crowned by the meme gods themselves, DogeKing now rules over all canine-themed tokens with benevolent wisdom. The tokenomics include a "Royal Treasury" where 2% of all transactions go to funding dog shelters worldwide.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@dogeking', 
  'woof@dogeking.io', 
  'https://twitter.com/dogeking', 
  'https://dexscreener.com/ethereum/0x2b3c4d5e', 
  TRUE, 
  'approved', 
  756
),
(
  'ShibaInu2.0', 
  '$SHIB2', 
  '0x3c4d5e6f7890abcdef1234567890abcdef123456', 
  'The next generation Shiba Inu with enhanced loyalty protocols and treat rewards.', 
  'ShibaInu2.0 was developed by a team of dog lovers and blockchain engineers who wanted to create the perfect digital pet. Unlike other dog coins, SHIB2 features a unique "Loyalty Mining" mechanism where holders earn treats (bonus tokens) based on how long they hold without selling. The longer you hold, the more loyal your digital Shiba becomes.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@shib2official', 
  'bark@shib2.io', 
  'https://twitter.com/shib2official', 
  'https://dexscreener.com/ethereum/0x3c4d5e6f', 
  FALSE, 
  'approved', 
  634
),
(
  'CatCoin Supreme', 
  '$CATSUPR', 
  '0x4d5e6f7890abcdef1234567890abcdef12345678', 
  'The feline answer to dog dominance, with 9 lives and infinite sass.', 
  'CatCoin Supreme was created by a mysterious figure known only as "The Cat Whisperer" who claimed to have received the tokenomics in a dream from an ancient Egyptian cat goddess. Each token represents one of the infinite sass points that cats possess, and holders gain voting rights in the "Feline Council" that decides which dog coins to ignore.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@catcoinsupreme', 
  'meow@catsupr.io', 
  'https://twitter.com/catcoinsupreme', 
  'https://dexscreener.com/ethereum/0x4d5e6f78', 
  TRUE, 
  'approved', 
  543
),
(
  'MonkeyBusiness', 
  '$MONKEY', 
  '0x5e6f7890abcdef1234567890abcdef1234567890', 
  'Swinging into DeFi with banana-powered smart contracts and jungle wisdom.', 
  'MonkeyBusiness started as a joke among primatologists who were also crypto enthusiasts. They created a token that mimics the social behavior of monkey troops, where holders can form "Troops" and share banana rewards. The more bananas (tokens) your troop holds collectively, the higher your position in the jungle hierarchy.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@monkeybiz', 
  'banana@monkey.biz', 
  'https://twitter.com/monkeybiz', 
  'https://dexscreener.com/ethereum/0x5e6f7890', 
  FALSE, 
  'approved', 
  421
),

-- DeFi Tokens
(
  'YieldFarm Pro', 
  '$YFPRO', 
  '0x6f7890abcdef1234567890abcdef12345678901a', 
  'Professional yield farming with automated strategies and compound rewards.', 
  'YieldFarm Pro was built by a team of former Wall Street quants who got tired of traditional finance and decided to bring institutional-grade yield farming to DeFi. The protocol automatically optimizes yield strategies across multiple chains and compounds rewards every block. Users can stake YFPRO to access premium farming vaults with higher APYs.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@yieldfarmPro', 
  'harvest@yfpro.finance', 
  'https://twitter.com/yieldfarmPro', 
  'https://dexscreener.com/ethereum/0x6f7890ab', 
  TRUE, 
  'approved', 
  387
),
(
  'LiquidityLock', 
  '$LLOCK', 
  '0x7890abcdef1234567890abcdef12345678901abc', 
  'Secure liquidity locking protocol with time-based release mechanisms.', 
  'LiquidityLock emerged from the need for trustless liquidity management in DeFi. The protocol allows projects to lock their liquidity for predetermined periods, giving investors confidence while enabling gradual unlocking based on milestones. LLOCK holders can vote on lock parameters and earn fees from the locking services.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@liquiditylock', 
  'secure@llock.finance', 
  'https://twitter.com/liquiditylock', 
  'https://dexscreener.com/ethereum/0x7890abcd', 
  FALSE, 
  'approved', 
  298
),
(
  'StakingRewards', 
  '$SREWARD', 
  '0x890abcdef1234567890abcdef12345678901abcd', 
  'Multi-chain staking protocol with dynamic reward distribution and governance.', 
  'StakingRewards was created to solve the fragmentation problem in staking across different blockchains. The protocol aggregates staking opportunities from multiple chains and automatically distributes rewards based on risk-adjusted returns. SREWARD token holders can propose new chains to add and vote on reward distribution parameters.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@stakingrewards', 
  'stake@sreward.io', 
  'https://twitter.com/stakingrewards', 
  'https://dexscreener.com/ethereum/0x890abcde', 
  TRUE, 
  'approved', 
  445
),

-- Gaming Tokens
(
  'GameFi Arena', 
  '$ARENA', 
  '0x90abcdef1234567890abcdef12345678901abcde', 
  'Play-to-earn gaming ecosystem with NFT battles and tournament rewards.', 
  'GameFi Arena was born from the vision of creating the ultimate gaming metaverse where players truly own their assets. The platform hosts tournaments across multiple games, with ARENA tokens as the universal currency. Players can stake their tokens to enter premium tournaments, and winners receive both ARENA rewards and exclusive NFTs.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@gamefiarena', 
  'play@arena.game', 
  'https://twitter.com/gamefiarena', 
  'https://dexscreener.com/ethereum/0x90abcdef', 
  TRUE, 
  'approved', 
  612
),
(
  'MetaQuest', 
  '$QUEST', 
  '0x0abcdef1234567890abcdef12345678901abcdef', 
  'Adventure-based gaming token with quest completion rewards and guild systems.', 
  'MetaQuest transforms traditional gaming quests into blockchain-based adventures where completion rewards real value. Players form guilds, complete quests together, and share QUEST token rewards. The more challenging the quest, the higher the rewards, creating a natural progression system that mirrors classic RPG mechanics.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@metaquest', 
  'adventure@quest.game', 
  'https://twitter.com/metaquest', 
  'https://dexscreener.com/ethereum/0x0abcdef1', 
  FALSE, 
  'approved', 
  356
),

-- AI/Tech Tokens
(
  'AIOracle', 
  '$AIORACLE', 
  '0xabcdef1234567890abcdef12345678901abcdef1', 
  'Decentralized AI oracle network providing real-world data with machine learning.', 
  'AIOracle combines artificial intelligence with blockchain oracles to provide the most accurate real-world data feeds. The AI models continuously learn and improve their predictions, while AIORACLE token holders can stake to run oracle nodes and earn rewards for providing accurate data. The network covers everything from weather to market predictions.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@aioracle', 
  'data@aioracle.ai', 
  'https://twitter.com/aioracle', 
  'https://dexscreener.com/ethereum/0xabcdef12', 
  TRUE, 
  'approved', 
  523
),
(
  'QuantumCompute', 
  '$QUANTUM', 
  '0xbcdef1234567890abcdef12345678901abcdef12', 
  'Quantum computing power marketplace with distributed processing rewards.', 
  'QuantumCompute is preparing for the quantum computing revolution by creating a marketplace where quantum processing power can be bought and sold. While true quantum computers are still emerging, the protocol simulates quantum algorithms and rewards QUANTUM holders who contribute classical computing power to the network.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@quantumcompute', 
  'quantum@qcompute.tech', 
  'https://twitter.com/quantumcompute', 
  'https://dexscreener.com/ethereum/0xbcdef123', 
  FALSE, 
  'approved', 
  234
),

-- Environmental/Green Tokens
(
  'CarbonOffset', 
  '$CARBON', 
  '0xcdef1234567890abcdef12345678901abcdef123', 
  'Environmental impact token for carbon offsetting and green project funding.', 
  'CarbonOffset was created by environmental scientists and blockchain developers who wanted to make carbon offsetting transparent and verifiable. Each CARBON token represents a verified carbon offset, and holders can burn tokens to offset their carbon footprint or stake them to fund new green projects around the world.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@carbonoffset', 
  'green@carbon.earth', 
  'https://twitter.com/carbonoffset', 
  'https://dexscreener.com/ethereum/0xcdef1234', 
  TRUE, 
  'approved', 
  467
),
(
  'SolarPower', 
  '$SOLAR', 
  '0xdef1234567890abcdef12345678901abcdef1234', 
  'Renewable energy token backed by solar panel installations and clean energy.', 
  'SolarPower represents ownership in a distributed network of solar panel installations. Token holders receive rewards based on the energy production of the solar farms, and can vote on new installation locations. The project aims to accelerate the adoption of renewable energy by making it profitable for communities to invest in solar infrastructure.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@solarpower', 
  'energy@solar.green', 
  'https://twitter.com/solarpower', 
  'https://dexscreener.com/ethereum/0xdef12345', 
  FALSE, 
  'approved', 
  389
),

-- Social/Community Tokens
(
  'SocialDAO', 
  '$SOCIAL', 
  '0xef1234567890abcdef12345678901abcdef12345', 
  'Decentralized social network governance token with content creator rewards.', 
  'SocialDAO is building the future of social media where users own their data and content creators are fairly compensated. SOCIAL token holders can vote on platform policies, moderate content through decentralized governance, and earn rewards for positive community contributions. The platform uses blockchain to ensure censorship resistance.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@socialdao', 
  'connect@social.dao', 
  'https://twitter.com/socialdao', 
  'https://dexscreener.com/ethereum/0xef123456', 
  TRUE, 
  'approved', 
  678
),
(
  'CreatorCoin', 
  '$CREATE', 
  '0xf1234567890abcdef12345678901abcdef123456', 
  'Platform for content creators to monetize their work through tokenized communities.', 
  'CreatorCoin enables content creators to launch their own tokens and build tokenized communities around their work. Fans can buy creator tokens to access exclusive content, participate in creator decisions, and share in the creator''s success. CREATE is the governance token that allows holders to vote on platform features and creator verification.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@creatorcoin', 
  'create@creator.coin', 
  'https://twitter.com/creatorcoin', 
  'https://dexscreener.com/ethereum/0xf1234567', 
  FALSE, 
  'approved', 
  445
),

-- More Meme/Fun Tokens
(
  'ToTheMoon', 
  '$MOON', 
  '0x1234567890abcdef12345678901abcdef1234567', 
  'The ultimate moonshot token with rocket-powered tokenomics and lunar rewards.', 
  'ToTheMoon was created by a group of space enthusiasts and crypto maximalists who believe that crypto will literally take humanity to the moon. The tokenomics include a "Rocket Fuel" mechanism where 3% of transactions are burned, reducing supply and increasing scarcity. Holders can stake MOON tokens to earn "Lunar Dust" rewards.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@tothemoon', 
  'rocket@moon.space', 
  'https://twitter.com/tothemoon', 
  'https://dexscreener.com/ethereum/0x12345678', 
  TRUE, 
  'approved', 
  834
),
(
  'DiamondHands', 
  '$DIAMOND', 
  '0x234567890abcdef12345678901abcdef12345678', 
  'For true HODLers with diamond hands and unshakeable conviction.', 
  'DiamondHands was born from the legendary diamond hands meme and rewards long-term holders with increasingly valuable benefits. The longer you hold without selling, the more "Diamond Dust" you accumulate, which can be used to access exclusive features and higher staking rewards. Paper hands are automatically detected and penalized.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@diamondhands', 
  'hodl@diamond.hands', 
  'https://twitter.com/diamondhands', 
  'https://dexscreener.com/ethereum/0x23456789', 
  FALSE, 
  'approved', 
  567
),
(
  'PaperHands', 
  '$PAPER', 
  '0x34567890abcdef12345678901abcdef123456789', 
  'The ironic token for those who sell too early but embrace the meme.', 
  'PaperHands is the satirical opposite of DiamondHands, created for traders who embrace their paper-handed nature. The token actually rewards quick trading and provides benefits for active traders rather than long-term holders. It''s become a favorite among day traders who appreciate the self-aware humor.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@paperhands', 
  'trade@paper.hands', 
  'https://twitter.com/paperhands', 
  'https://dexscreener.com/ethereum/0x34567890', 
  FALSE, 
  'approved', 
  234
),
(
  'WagmiCoin', 
  '$WAGMI', 
  '0x4567890abcdef12345678901abcdef1234567890', 
  'We''re All Gonna Make It - the ultimate optimism token for crypto believers.', 
  'WagmiCoin embodies the eternal optimism of the crypto community with the belief that "We''re All Gonna Make It." The token features a unique "Optimism Engine" that increases rewards during market downturns, helping holders stay positive during tough times. Community members share success stories and support each other through the WAGMI DAO.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@wagmicoin', 
  'wagmi@wagmi.coin', 
  'https://twitter.com/wagmicoin', 
  'https://dexscreener.com/ethereum/0x45678901', 
  TRUE, 
  'approved', 
  723
),

-- NFT/Art Tokens
(
  'ArtisticSoul', 
  '$ARTSOUL', 
  '0x567890abcdef12345678901abcdef12345678901', 
  'Empowering digital artists with fair royalties and community-driven curation.', 
  'ArtisticSoul was created by a collective of digital artists who were frustrated with traditional NFT platforms taking large cuts of their sales. The platform ensures artists receive fair royalties in perpetuity, and ARTSOUL holders can vote on which artists to feature and support through community grants.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@artisticsoul', 
  'create@artsoul.art', 
  'https://twitter.com/artisticsoul', 
  'https://dexscreener.com/ethereum/0x56789012', 
  FALSE, 
  'approved', 
  345
),
(
  'PixelPerfect', 
  '$PIXEL', 
  '0x67890abcdef12345678901abcdef123456789012', 
  'Retro pixel art NFT ecosystem with 8-bit gaming nostalgia and collectibles.', 
  'PixelPerfect brings back the golden age of 8-bit gaming through blockchain collectibles. Each PIXEL token can be used to mint procedurally generated pixel art NFTs, and holders can participate in retro gaming tournaments where winners receive rare pixel art prizes. The community is building a full 8-bit metaverse.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@pixelperfect', 
  'pixel@perfect.art', 
  'https://twitter.com/pixelperfect', 
  'https://dexscreener.com/ethereum/0x67890123', 
  TRUE, 
  'approved', 
  456
),

-- Food/Lifestyle Tokens
(
  'PizzaDAO', 
  '$PIZZA', 
  '0x7890abcdef12345678901abcdef1234567890123', 
  'Decentralized pizza ordering and restaurant rewards with cheesy tokenomics.', 
  'PizzaDAO started as a joke but became a real utility token when pizza restaurants began accepting it for payments. The DAO votes on new restaurant partnerships, and PIZZA holders get discounts at participating locations. The "Cheese Rewards" program gives extra tokens for trying new pizza combinations.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@pizzadao', 
  'slice@pizza.dao', 
  'https://twitter.com/pizzadao', 
  'https://dexscreener.com/ethereum/0x78901234', 
  FALSE, 
  'approved', 
  567
),
(
  'CoffeeChain', 
  '$COFFEE', 
  '0x890abcdef12345678901abcdef12345678901234', 
  'Global coffee supply chain transparency with bean-to-cup traceability.', 
  'CoffeeChain uses blockchain to create complete transparency in the coffee supply chain, from bean farmers to your morning cup. COFFEE token holders can trace their coffee''s journey, support specific farmers directly, and earn rewards for choosing ethically sourced coffee. The platform has partnered with coffee shops worldwide.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@coffeechain', 
  'brew@coffee.chain', 
  'https://twitter.com/coffeechain', 
  'https://dexscreener.com/ethereum/0x89012345', 
  TRUE, 
  'approved', 
  389
),

-- Sports/Fitness Tokens
(
  'FitnessFi', 
  '$FITFI', 
  '0x90abcdef12345678901abcdef123456789012345', 
  'Move-to-earn fitness ecosystem with workout rewards and health tracking.', 
  'FitnessFi gamifies fitness by rewarding users with FITFI tokens for completing workouts, hitting step goals, and maintaining healthy habits. The app integrates with popular fitness trackers and uses AI to verify workout authenticity. Users can stake tokens to access premium workout plans and compete in fitness challenges.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@fitnessfi', 
  'move@fitfi.health', 
  'https://twitter.com/fitnessfi', 
  'https://dexscreener.com/ethereum/0x90123456', 
  FALSE, 
  'approved', 
  445
),
(
  'SportsFan', 
  '$FANTOKEN', 
  '0x0123456789abcdef12345678901abcdef1234567', 
  'Universal sports fan token with team voting rights and exclusive experiences.', 
  'SportsFan allows fans to support their favorite teams across all sports through a single token. FANTOKEN holders can vote on team decisions, access exclusive content, and earn rewards for accurate game predictions. The platform partners with sports teams to offer unique fan experiences and merchandise.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@sportsfan', 
  'cheer@fan.token', 
  'https://twitter.com/sportsfan', 
  'https://dexscreener.com/ethereum/0x01234567', 
  TRUE, 
  'approved', 
  612
),

-- Music/Entertainment Tokens
(
  'MusicDAO', 
  '$MUSIC', 
  '0x123456789abcdef12345678901abcdef12345678', 
  'Decentralized music platform with artist royalties and fan governance.', 
  'MusicDAO is revolutionizing the music industry by giving artists fair royalties and fans a voice in music curation. MUSIC token holders can vote on which artists to promote, fund new album productions, and earn rewards for discovering new talent. Artists keep 90% of their royalties, with 10% going to the community treasury.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@musicdao', 
  'harmony@music.dao', 
  'https://twitter.com/musicdao', 
  'https://dexscreener.com/ethereum/0x12345678', 
  TRUE, 
  'approved', 
  534
),
(
  'StreamRewards', 
  '$STREAM', 
  '0x23456789abcdef12345678901abcdef123456789', 
  'Streaming platform token with viewer rewards and content creator support.', 
  'StreamRewards transforms passive streaming into an active, rewarding experience. Viewers earn STREAM tokens for watching content, engaging with creators, and participating in live chats. Creators receive additional token rewards based on viewer engagement, creating a positive feedback loop that benefits everyone in the ecosystem.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@streamrewards', 
  'watch@stream.rewards', 
  'https://twitter.com/streamrewards', 
  'https://dexscreener.com/ethereum/0x23456789', 
  FALSE, 
  'approved', 
  423
),

-- Travel/Adventure Tokens
(
  'WanderlustCoin', 
  '$WANDER', 
  '0x3456789abcdef12345678901abcdef1234567890', 
  'Travel rewards token with destination discovery and adventure funding.', 
  'WanderlustCoin was created by digital nomads who wanted to gamify travel and exploration. WANDER holders earn rewards for visiting new destinations, sharing travel experiences, and helping other travelers. The platform includes a decentralized travel booking system where users can pay with WANDER tokens and earn cashback.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@wanderlustcoin', 
  'explore@wander.travel', 
  'https://twitter.com/wanderlustcoin', 
  'https://dexscreener.com/ethereum/0x34567890', 
  FALSE, 
  'approved', 
  367
),

-- Education/Learning Tokens
(
  'LearnToEarn', 
  '$LEARN', 
  '0x456789abcdef12345678901abcdef12345678901', 
  'Educational platform token rewarding knowledge acquisition and skill development.', 
  'LearnToEarn incentivizes education by rewarding students with LEARN tokens for completing courses, passing exams, and achieving learning milestones. The platform covers everything from basic literacy to advanced technical skills, with token rewards scaled to the difficulty and importance of the subject matter.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@learntoearn', 
  'study@learn.earn', 
  'https://twitter.com/learntoearn', 
  'https://dexscreener.com/ethereum/0x45678901', 
  TRUE, 
  'approved', 
  489
),

-- Health/Medical Tokens
(
  'HealthChain', 
  '$HEALTH', 
  '0x56789abcdef12345678901abcdef123456789012', 
  'Decentralized health records with privacy protection and research rewards.', 
  'HealthChain securely stores health records on blockchain while maintaining patient privacy through advanced encryption. Patients own their data and can choose to share anonymized information with researchers in exchange for HEALTH tokens. The platform aims to accelerate medical research while giving patients control over their health data.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@healthchain', 
  'care@health.chain', 
  'https://twitter.com/healthchain', 
  'https://dexscreener.com/ethereum/0x56789012', 
  FALSE, 
  'approved', 
  345
),

-- Real Estate/Property Tokens
(
  'PropertyDAO', 
  '$PROP', 
  '0x6789abcdef12345678901abcdef1234567890123', 
  'Fractional real estate ownership with rental income distribution and governance.', 
  'PropertyDAO enables fractional ownership of real estate properties through blockchain tokenization. PROP holders receive proportional rental income from the property portfolio and can vote on new property acquisitions. The platform makes real estate investment accessible to everyone, regardless of their capital size.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@propertydao', 
  'invest@prop.dao', 
  'https://twitter.com/propertydao', 
  'https://dexscreener.com/ethereum/0x67890123', 
  TRUE, 
  'approved', 
  456
),

-- Charity/Social Impact Tokens
(
  'CharityChain', 
  '$CHARITY', 
  '0x789abcdef12345678901abcdef12345678901234', 
  'Transparent charity donations with impact tracking and community voting.', 
  'CharityChain brings transparency to charitable giving by tracking every donation from source to impact. CHARITY token holders can vote on which causes to support, and all donations are publicly verifiable on the blockchain. The platform has partnered with major charities worldwide to ensure maximum impact.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@charitychain', 
  'give@charity.chain', 
  'https://twitter.com/charitychain', 
  'https://dexscreener.com/ethereum/0x78901234', 
  FALSE, 
  'approved', 
  567
),

-- Technology/Innovation Tokens
(
  'InnovateDAO', 
  '$INNOVATE', 
  '0x89abcdef12345678901abcdef123456789012345', 
  'Funding breakthrough innovations with community-driven research grants.', 
  'InnovateDAO funds cutting-edge research and development projects through community governance. INNOVATE holders can propose research projects, vote on funding allocation, and share in the intellectual property rights of successful innovations. The DAO has already funded several breakthrough technologies in renewable energy and biotechnology.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@innovatedao', 
  'research@innovate.dao', 
  'https://twitter.com/innovatedao', 
  'https://dexscreener.com/ethereum/0x89012345', 
  TRUE, 
  'approved', 
  423
),

-- Space/Astronomy Tokens
(
  'SpaceExplorer', 
  '$SPACE', 
  '0x9abcdef12345678901abcdef1234567890123456', 
  'Funding space exploration missions with cosmic rewards and stellar governance.', 
  'SpaceExplorer funds real space exploration missions and research projects. SPACE holders can vote on which missions to support, from asteroid mining to Mars colonization research. The token has partnerships with space agencies and private space companies, giving holders unique access to space mission updates and exclusive content.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@spaceexplorer', 
  'mission@space.explorer', 
  'https://twitter.com/spaceexplorer', 
  'https://dexscreener.com/ethereum/0x90123456', 
  FALSE, 
  'approved', 
  389
),

-- Final few tokens to reach 45
(
  'MemeLord', 
  '$MEMELORD', 
  '0xabcdef12345678901abcdef12345678901234567', 
  'The ultimate meme aggregator with viral content rewards and meme battles.', 
  'MemeLord is the final boss of meme tokens, created by the collective consciousness of internet culture. Holders can submit memes for community voting, with winning memes earning MEMELORD rewards. The platform hosts epic meme battles where the funniest content creators compete for legendary status and token prizes.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@memelord', 
  'meme@lord.meme', 
  'https://twitter.com/memelord', 
  'https://dexscreener.com/ethereum/0x01234567', 
  TRUE, 
  'approved', 
  999
),
(
  'RocketFuel', 
  '$FUEL', 
  '0xbcdef12345678901abcdef123456789012345678', 
  'High-octane DeFi protocol with turbo-charged yields and rocket-powered APY.', 
  'RocketFuel is the high-performance DeFi protocol that promises to launch your portfolio into orbit. With innovative yield optimization strategies and a unique "Turbo Mode" that compounds rewards every block, FUEL holders experience astronomical returns. The protocol''s rocket-themed gamification makes DeFi fun and engaging.',
  '/placeholder.svg?height=200&width=200', 
  'Owner', 
  '@rocketfuel', 
  'boost@rocket.fuel', 
  'https://twitter.com/rocketfuel', 
  'https://dexscreener.com/ethereum/0x12345678', 
  FALSE, 
  'approved', 
  445
),
(
  'CommunityFirst', 
  '$COMMUNITY', 
  '0xcdef12345678901abcdef1234567890123456789', 
  'Community-owned platform with democratic governance and shared prosperity.', 
  'CommunityFirst puts community ownership at the center of everything. Every major decision is made through democratic voting, and all platform profits are shared among COMMUNITY holders. The platform includes social features, governance tools, and economic incentives that align individual success with community prosperity.',
  '/placeholder.svg?height=200&width=200', 
  'Community', 
  '@communityfirst', 
  'together@community.first', 
  'https://twitter.com/communityfirst', 
  'https://dexscreener.com/ethereum/0x23456789', 
  TRUE, 
  'approved', 
  678
);
